she_codes_news/news/urls.py
from django.urls import path, include
from . import views
# from . import views
from users.apps import UsersConfig
from  .views import IndexView, StoryView, AddStoryView, UpdateStoryView, DeleteStoryView, CreateAccountView, AddCommentView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name= 'story'),
    path('add-story/', views.AddStoryView.as_view(), name= 'createStory'),
    path('update-story/<int:pk>/', views.UpdateStoryView.as_view(), name= 'updateStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name= 'deleteStory'),
    # path('author/<str:username>', SearchAuthorView.as_view(), name='authorSearch'),
    path('add-comment/<int:pk>/', views.AddCommentView.as_view(), name='addComment'),
    path('users/', include('users.urls')),    
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/users/urls.py
from django.urls import path
from .views import CreateAccountView, account_view, UpdateProfileView
from django.contrib.auth import views as auth_views
from . import views
app_name = 'users'

urlpatterns = [
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    path('update-profile/<int:pk>', views.UpdateProfileView.as_view(), name='update_profile'),
    path('account/', account_view, name='account'),
    
]

she_codes_news/templates/base.html
{% load static %}

<!doctype html>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Keerthi">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %} {% endblock %}
    </head>

    <body>
        <header>
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        <!-- content blocks here -->
        {% block content %} {% endblock %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    {% if request.user.is_authenticated %}
     <ul>
        <li><a href="#"> Welcome, {{user.username}} </a></li>
        <li><a href="{% url 'news:createStory' %}">Write New Story</a></li>
        <li><a href="{% url 'news:profile' %}">Profile</a></li>
        <li><a href="{% url 'news:myStories' %}">My Stories</a></li>
        <li><a href="{% url 'news:myFavourites' %}">My Favourites</a></li>
     </ul>
      
      <a href="{% url 'logout' %}">Logout</a>
    {% else %}  
     <ul>
        <li><a href="{% url 'news:index' %}">Home</a></li>
        <li><a href="{% url 'login' %}">Login</a></li>
        <li><a href="{% url 'news:createAccount' %}">Create Account</a></li>
    </ul>
    {% endif %}  
       
</nav>