she_codes_news/news/urls.py
from django.urls import path, include
from . import views
# from . import views
from users.apps import UsersConfig
from  .views import IndexView, StoryView, AddStoryView, UpdateStoryView, DeleteStoryView, CreateAccountView, AddCommentView

app_name = 'news'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name= 'story'),
    path('add-story/', views.AddStoryView.as_view(), name= 'createStory'),
    path('update-story/<int:pk>/', views.UpdateStoryView.as_view(), name= 'updateStory'),
    path('delete-story/<int:pk>/', views.DeleteStoryView.as_view(), name= 'deleteStory'),
    # path('author/<str:username>', SearchAuthorView.as_view(), name='authorSearch'),
    path('add-comment/<int:pk>/', views.AddCommentView.as_view(), name='addComment'),
    path('users/', include('users.urls')),    
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

she_codes_news/news/models.py
from django.db import models
from django.contrib.auth import get_user_model

class NewsStory(models.Model):

    CategoryRange = models.TextChoices('CategoryRange', 'World Politics Business Technology Science Sports Entertainment Health')
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    content = models.TextField()
    image_url = models.CharField(max_length=200)
    category = models.CharField(max_length=200 , choices=CategoryRange.choices, default=CategoryRange.World)
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='stories')

    
    def __str__(self):
        return self.title
    
# class StoryCategory(models.Model):
#     category = models.CharField(max_length=200)
    
    def __str__(self):
        return self.category

class Comment(models.Model):
    comment = models.TextField()
    body = models.TextField()
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, related_name='comments')
    story = models.ForeignKey(NewsStory, on_delete=models.CASCADE, related_name='comments')
    
    def __str__(self):
        return 'Comment {} by {}'.format(self.comment, self.author)

she_codes_news/news/forms.py
from django import forms
from django.forms import ModelForm
from .models import NewsStory, Comment
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

class StoryForm(ModelForm): 
    exclude = ['pub_date']
    class Meta:
        model = NewsStory
        fields = ['title', 'content', 'image_url','category']
        widgets = {
            'title': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Title'}),
            'content': forms.Textarea(attrs = {'class': 'form-control', 'placeholder': 'Content'}),
            'image_url': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Image URL'}),
            'category': forms.TextInput(attrs = {'class': 'form-control', 'placeholder': 'Category'}),
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['comment','body']
        widgets = {
            'comment': forms.Textarea(attrs = {'class': 'form-control', 'placeholder': 'Comment'}),
            'body': forms.Textarea(attrs = {'class': 'form-control', 'placeholder': 'Body'}),
        }        

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')
           
            
            
                                        
                                        

she_codes_news/news/views.py
from django.forms import BaseModelForm
from django.shortcuts import render,redirect, get_object_or_404
from django.db.models import Q
# from django.contrib.auth.models import get_user_model
from django.views import generic
from django.urls import reverse_lazy
from .models import NewsStory
from .forms import StoryForm, CommentForm
from .forms import CustomUserCreationForm
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth import get_user_model
# from . users import SearchAuthorView


class CreateAccountView (generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/createAccount.html'

    def form_valid(self,form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class IndexView(generic.ListView):
    template_name = 'news/index.html'
    context_object_name = "all_stories"

    def get_queryset(self):
        '''Return all news stories.'''
        return NewsStory.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_stories'] = NewsStory.objects.all()[:4]
        return context

class StoryView(generic.DetailView):
    model = NewsStory
    template_name = 'news/story.html'
    context_object_name = "story"

class AddStoryView(generic.CreateView):
        form_class = StoryForm
        context_object_name = 'storyform'
        template_name = 'news/createStory.html'
        success_url = reverse_lazy('news:index')

        def form_valid(self,form):
            form.instance.author = self.request.user
            return super().form_valid(form)

class UpdateStoryView(generic.UpdateView):
        model = NewsStory
        form_class = StoryForm
        context_object_name = 'storyform'
        template_name = 'news/updateStory.html'
        success_url = reverse_lazy('news:index')

        def form_valid(self,form):
            form.instance.author = self.request.user
            return super().form_valid(form)


class DeleteStoryView(generic.DeleteView):
        model = NewsStory
        context_object_name = 'storyform'
        template_name = 'news/deleteStory.html'
        success_url = reverse_lazy('news:index') 

        def form_valid(self,form):
            form.instance.author = self.request.user
            return super().form_valid(form)       
     
class AddCommentView(generic.CreateView):
        model = NewsStory
        form_class = CommentForm
        context_object_name = 'commentform'
        template_name = 'news/addComment.html'
        success_url = reverse_lazy('news:index')

        def form_valid(self,form):
            form.instance.author = self.request.user
            return super().form_valid(form)

class CategoryView(generic.ListView):
    template_name = 'news'
    context_object_name = 'category'
    model = NewsStory

    def get_queryset(self):
        return StoryCategory.objects.filter(category=self.kwargs['category'])
               

she_codes_news/news/templates/news/authorSearch.html
{% extends 'base.html' %}
{% load static %}

{% block stylesheets %}
<link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"/>
{% endblock %}
{% block content %}
<h1>Authored by {{author.username}}</h1>
{% if all_stories %}
    <ul>
        {% for story in all_stories %}
            {% include './storyCard.html' story=story %}
        {% endfor %}
    </ul>
{% else %}
    <p>No stories found.</p>
{% endif %}
{% endblock %}

she_codes_news/news/templates/news/comments.html
{% extends 'base.html'%}
{% load static %}
{% block stylesheets%}
<link rel="stylesheet" type="text/css"  href="{% static 'news/styles.css' %}"/>
{% endblock %}

{% block content %}
   <h1 >Comments</h1>
    <h2 >Tell us what you think</h2>
    <h2 >Write a Comment </h2>
    
{% endblock %}

she_codes_news/news/templates/news/createStory.html
{% extends "base.html" %}

{% block content %}

   <h1>Tell us a Story</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>

    {% endblock %}

she_codes_news/news/templates/news/deleteStory.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
<link rel="stylesheet"  type="text/css"  href="{% static 'news/styles.css' %}"/>

{% endblock %}
{% block content %}
<h1>Edit Story</h1>

<h2>Are you sure you want to delete the story?</h2>

<form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete">
</form>
    
    {% endblock %}
    

she_codes_news/news/templates/news/index.html
    {% extends "base.html" %}
    {% load static %}

    {% block stylesheets %}
      <link rel="stylesheet"  type="text/css" href="{% static 'news/styles.css' %}">
      {% endblock %}
    {% block content %}
    <br>
    <a href="{% url 'news:createStory' %}">Write New Story</a>
    <h2>Latest News</h2>

    <div id="latest-stories">
        {% if latest_stories %}
            {% for story in latest_stories %}
                {% include "./storyCard.html" with story=story position=forloop.counter %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>

    <div id="all-stories">
        {% if latest_stories %}
            {% for story in all_stories %}
               {% include "./storyCard.html" with story=story %}
            {% endfor %}
        {% else %}
            <p>No stories are available.</p>
        {% endif %}
    </div>
    {% endblock %}

she_codes_news/news/templates/news/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Search</h2>
<form action="{% url 'news:search' %}" method="get">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="text" name="q" placeholder="Search...">
    <input type="submit" value="Search">
</form>

{% if stories %}
<ul>
    {% for story in stories %}
        <h2> {{story.title}} </h2>
        <p> Content: {{story.content}} </p>
        <p> Authored by: {{story.author}} </p>
        <p> Published on: {{story.pub_date}} </p>
        <p> Category:  {{ story.get_category_display }}</p>
    {% endfor %}
</ul>
{% else %}
    <p>No stories found.</p>
{% endif %}
{% endblock %}







    

she_codes_news/news/templates/news/story.html
{% extends "base.html %"}
{% load static %}

{% block stylesheets %}
  <link rel="stylesheet" type="text/css"  href="{% static 'news/styles.css' %}">
    {% endblock %}

    {% block content %}

<div id="story-wrapper">
    <h2>{{ story.title }}</h2>
    <h4>{{ story.author }}</h4>
    <div id="story-content">
        <img src="{% static '/news/images/placeholder-5.jpg' %}">
        {{ story.content|linebreaks }}
    </div>
</div>

<section>
    <h3>Comments</h3>
    {% if story.comments.all %}
        <ul>
            {% for comment in story.comments.all %}
                <li>
                    <p>Content : {{ comment.content }}</p>
                    <p>Author: {{ comment.author }}</p>
                    <p> Published: {{ comment.pub_date }}</p>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No comments yet.</p>
    {% endif %}
</section>

{% endblock %}

she_codes_news/news/templates/news/storyCard.html
    <a href="{% url 'news:story' story.id %}">
        {% if position < 5 %}
            <img src="../static/news/images/placeholder-{{ position }}.jpg">
        {% else %}
            <img src="https://picsum.photos/600">
        {% endif %}
        <div class="story-card-text">
            <h3>{{ story.title }} 
                {% if request.user.is_authenticate %} <a href="{% url 'news:updateStory' story.id %}"><small>Edit </small></a>
                 <a href="{% url 'news:deleteStory' story.id %}"> <small>Delete</small></a>  
                 {% endif %}
                </h3>
                <h4> {{story.get_category_display}} </h4>
            <h4><small>Authored by</small> <a class="link" href="{% url 'news:authorSearch' story.author %}"> {{story.author}} </a></h4>
            <h4>{{ story.pub_date }}</h4>
        </div>
    </a>
</div>

she_codes_news/news/templates/news/updateStory.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheets %}
 <link rel="stylesheet" type="text/css" href="{% static 'news/styles.css' %}"/>
 {% endblock %}

 {% block content %}

 <h1>Edit Story</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
    
        {% endblock %}